# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            AI Saturdays @ KTR
tagline:          'Empowering anyone to be kickass in AI'
description:      'Empowering anyone to be kickass in AI'
url:              https://ai6ktr.github.io/
baseurl:          /

author:
  name:           'Niladri Shekhar Dutt'
  url:            https://ai6ktr.github.io/

paginate:         5
